### ISSUE TITLE
Doesn't work when creating the apk for the non-app module

### ISSUE THREAD

**Issue by barry-irvine** [bitrise-steplib/bitrise-step-android-build-for-ui-testing#20] opened 2021-11-11 09:52 UTC
Step version 1.1.5 (latest)
Happens EVERY TIME

### Issue description

If I try to build a test apk for one of my submodules it runs the command okay but then doesn't seem to be able to find the apk. E.g. when I create a build for the variant `debug` and the module `design` I get the error message below.

If I run the same command locally I can see the apk where I'd expect to see it `design/build/outputs/apk/androidTest/debug/design-debug-androidTest.apk`

### Bitrise info

- Build URL: https://app.bitrise.io/build/4382b2f6-d572-4a5f-a1cc-01619e7ec1f2
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES_
- Log: 

<details>
  <pre>
 Export [ design-debug-androidTest.apk => $BITRISE_DEPLOY_DIR/design-debug-androidTest.apk ]
Could not find the exported app APK  </pre>
</details>

### Steps to reproduce

1. Create a UI Test on an android-library submodule
2. Confirm that it is possible to create or even run the UI test locally. E.g. `./gradlew mymodule:aDAT` or `./gradlew mymodule:cDAT`
3. Add the `android-build-for-ui-testing` step to your bitrise flow and set the module to `mymodule` and the variant to `debug`
4. Run the flow. It appears that the file is generated but it is unable to export it to the DEPLOY_DIR

**Comment by ofalvai** [comment] 2021-11-15 12:05
@barry-irvine What happens here is that the step tries to export the second APK (not the test, but the main one) and fails at that. Can you check locally the path of this main APK? 

We tried to reproduce the issue, but couldn't make it fail in our test projects, so we would appreciate some help about what is different in your setup.

**Comment by iomy** [comment] 2021-11-18 22:44
Same issue here. Nothing in your module or bitrise setup has changed. We are building an apk of the library module and one of the app module (as suggested [here](https://discuss.bitrise.io/t/vdt-not-able-to-run-instrumentation-tests-on-android-library-project/3197/7))- this was working in the past. 

Built run:
`$ /bitrise/src/gradlew ":lib-android:assembleDebug" ":lib-android:assembleDebugAndroidTest" ":app:assembleDevelopmentDebug"
`

Output: 
`  Export [ lib-debug-androidTest.apk => $BITRISE_DEPLOY_DIR/lib-debug-androidTest.apk ]
Could not find the exported app APK`

**Comment by ofalvai** [comment] 2021-11-22 16:06
Hey everyone, we finally found the root cause and fixed it in #21 (see the PR description for details).

Version 0.1.7 of this step is released with the fix, please try it in your workflows. I'm closing this issue, but let us know if you still experience problems with the step.

**Closed by ofalvai** 2021-11-22 16:06 UTC
